global:
  dependencies:
    python:
      - forge-sdk==4.0.0a3
      - forge-cli==4.0.0a1
      - cecs==4.0.0a0
      - services/*.py
  env:
    PROJECT_NAME: "Kaliopa"
    PROJECT_SLUG: "kaliopa"

    ENVIRONMENT_NAME: {{ env.CI_COMMIT_REF_SLUG }}
    MODULE: '{{ env.MODULE | default("local", True) }}'
    LOG_LEVEL: INFO

    # Messaging
    PULSAR_URL: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    COMPRESSION_TYPE: LZ4
    SUBSCRIPTION_TYPE: Shared
    SUBSCRIPTION_INITIAL_POSITION: Earliest

    # Databases
    MONGO_CLIENT_HOST: mongodb:27017
    MONGO_CLIENT_USERNAME: root

    POSTGRES_CLIENT_HOST: postgresql
    POSTGRES_CLIENT_PORT: '5432'
    POSTGRES_CLIENT_USERNAME: postgres

    REDIS_CLIENT_HOST: redis-master
    REDIS_CLIENT_PORT: '6379'
    REDIS_URL: redis-master:6379

    BACKUP_CONTAINER_NAME: '{{ env.BACKUP_CONTAINER_NAME }}'
    BACKUPS_STORAGE_ACCOUNT_NAME: '{{ env.BACKUPS_STORAGE_ACCOUNT_NAME }}'

    # Misc
    UNLEASH_URL: http://unleash:4242/api
    UNLEASH_API_TOKEN: '{{ env.UNLEASH_API_TOKEN }}'

    DEFAULT_TIME_ZONE: Europe/Zagreb

  secrets:
    SENTRY_DSN: '{{ env.SENTRY_DSN }}'

    MONGO_CLIENT_PASSWORD: knopso123
    MONGO_URL: mongodb://root:knopso123@mongodb:27017
    POSTGRES_CLIENT_PASSWORD: knopso123

    BACKUPS_STORAGE_ACCOUNT_KEY: '{{ env.BACKUPS_STORAGE_ACCOUNT_KEY }}'
    BACKUPS_ZIP_ENCRYPT: '{{ env.BACKUPS_ZIP_ENCRYPT }}'

  backups:
    mongo:
      enabled: true
      cron: "3 5,17 * * *"
    postgres:
      enabled: true
      cron: "8 5,17 * * *"
    redis:
      enabled: true
      cron: "13 5,17 * * *"

  cecs:
    params: "-e venv"

  repository: "nexus.vingd.net"

services:
  rule-engine:
    type: java
    resources:
      cpu: 500m
      memory: 650Mi

  heartbeat-scheduler:
    package: heartbeat
    type: python
    version: 4.0.0a3
    env:
      HEARTBEAT_CYCLE: 5
    db:
      mongo: true
    dependencies:
      - rule-engine
    resources:
      cpu: 69m
      memory: 65Mi

  heartbeat-sender:
    package: heartbeat
    type: python
    version: 4.0.0a3
    db:
      mongo: true
    dependencies:
      - rule-engine
    resources:
      cpu: 84m
      memory: 94Mi
  telegram-adapter:
    type: python
    version: 4.0.0a7
    db:
      mongo: true
    env:
      TELEGRAM_BOT_TOKEN: "{{env.TELEGRAM_BOT_TOKEN}}"
    resources:
      cpu: 81m
      memory: 130Mi
  gpt3-adapter:
    type: python
    version: 4.0.0a6
    env:
      OPENAI_API_KEY: "{{env.OPENAI_API_KEY}}"
    resources:
      cpu: 81m
      memory: 130Mi
  google-translate-adapter:
    type: python
    db:
      mongo: true
    resources:
      cpu: 100m
      memory: 100Mi
    env:
      GOOGLE_TRANSLATE_API_KEY: "{{env.GOOGLE_TRANSLATE_API_KEY}}"
